name: Kettlecount
options:
  bundleIdPrefix: com.shimondeitel.kettlecount
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Kettlecount:
    type: application
    platform: iOS
    sources:
      - path: Kettlecount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.kettlecount
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Kettlecount/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  KettlecountTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KettlecountTests
      - path: Kettlecount.storekit
    dependencies:
      - target: Kettlecount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.kettlecount.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  KettlecountUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: KettlecountUITests
    dependencies:
      - target: Kettlecount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.kettlecount.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Kettlecount:
    build:
      targets:
        Kettlecount: all
        KettlecountTests: [test]
        KettlecountUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Kettlecount.storekit
    test:
      config: Debug
      storeKitConfiguration: Kettlecount.storekit
      targets:
        - KettlecountTests
        - KettlecountUITests
    archive:
      config: Release
